[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ocentra_games = "7eWx3H8bXMif7SDyPS1j5LZw1yUGDNZY592WzEKNf696"

[programs.mainnet]
ocentra_games = "7eWx3H8bXMif7SDyPS1j5LZw1yUGDNZY592WzEKNf696"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"  # Use local validator for tests (faster, no airdrop limits)
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --require ./tests/root-hooks.ts tests/**/*.ts"
